# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: EKS-course-cluster
#   region: ap-southeast-1

# nodeGroups:
#   - name: ng-1
#     instanceType: t2.small
#     desiredCapacity: 2
#     ssh: # use existing EC2 key
#       publicKeyName: /Users/rupeshpanwar/Documents/project/AWS-EKS-Tutorial/c-EKS-Setup/c.a-eksctl/eks-course.pem

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2

#6 8:58 [ℹ]  nodegroup "ng-1" has 2 node(s)
# 2021-11-25 15:58:58 [ℹ]  node "ip-192-168-38-233.ap-southeast-1.compute.internal" is ready
# 2021-11-25 15:58:58 [ℹ]  node "ip-192-168-77-120.ap-southeast-1.compute.internal" is ready
# 2021-11-25 15:58:59 [ℹ]  kubectl command should work with "/Users/rupeshpanwar/.kube/config", try 'kubectl get nodes'
# 2021-11-25 15:58:59 [✔]  EKS cluster "basic-cluster" in "ap-southeast-1" region is ready

# c.a-eksctl $ kubectl get nodes
# NAME                                                STATUS   ROLES    AGE     VERSION
# ip-192-168-38-233.ap-southeast-1.compute.internal   Ready    <none>   4m42s   v1.21.5-eks-bc4871b
# ip-192-168-77-120.ap-southeast-1.compute.internal   Ready    <none>   4m49s   v1.21.5-eks-bc4871b
    